version: '3.4'

networks:
  dev:
    driver: bridge

services:
  mindfulnessapi:
    image: ${DOCKER_REGISTRY-}mindfulnessapi
    depends_on:
     - "mindfulness_db"
    container_name: mindfulnessapi-service
    build:
      context: .
      dockerfile: MindfulnessApi/Dockerfile
    networks:
      - dev
  mindfulness_db:
    image: postgres:latest
    container_name: mindfulness_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDriverDb
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data: